# Generated by Django 5.0.1 on 2024-01-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "itemId",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("itemName", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=50)),
                ("pictureURL", models.CharField(max_length=50)),
            ],
        ),
    ]
