# Generated by Django 5.0.1 on 2024-01-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bookId", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("publish_Date", models.DateField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
